apiVersion: skaffold/v1
kind: Config
metadata:
  name: vertx-backend
build:
  artifacts:
    - image: vertx-backend/crud
      jib:
        type: gradle
        project: crud
      context: .
    - image: vertx-backend/public-api
      jib:
        type: gradle
        project: public-api
      context: .
    - image: vertx-backend/relays-communication
      jib:
        type: gradle
        project: relays-communication
      context: .
    - image: vertx-backend/triangulation
      docker:
        dockerfile: Dockerfile
      context: triangulation
deploy:
  kubectl:
    manifests:
      - "crud/src/k8s/*.yaml"
      - "public-api/src/k8s/*.yaml"
      - "relays-communication/src/k8s/*.yaml"
      - "triangulation/src/k8s/*.yaml"