apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-public-api
  labels:
    app: public-api
spec:
  endpoints:
    - interval: 30s
      port: http
  selector:
    matchLabels:
      app: public-api
