apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: public-api
  name: public-api
spec:
  selector:
    matchLabels:
      app: public-api
  template:
    metadata:
      labels:
        app: public-api
    spec:
      containers:
        - image: vertx-backend/public-api:latest
          name: public-api
          env:
            - name: CRUD_HOST
              valueFrom:
                configMapKeyRef:
                  name: crud-config
                  key: crud_hostname
            - name: CRUD_PORT
              valueFrom:
                configMapKeyRef:
                  name: crud-config
                  key: crud_port
