apiVersion: v1
kind: Service
metadata:
  labels:
    app: public-api
    vertx-backend: hazelcast
  name: public-api
spec:
  type: ClusterIP
  selector:
    app: public-api
  ports:
    - name: hazelcast
      port: 5701
