apiVersion: v1
kind: Service
metadata:
  labels:
    app: public-api
  name: public-api
spec:
  type: LoadBalancer
  selector:
    app: public-api
  ports:
    - name: http
      port: 4000
    - name: hazelcast
      port: 5701
