apiVersion: v1
kind: Service
metadata:
  labels:
    app: relays-communication
  name: relays-communication
spec:
  type: LoadBalancer
  selector:
    app: relays-communication
  ports:
    - name: mqtt
      port: 8883
