openapi: 3.0.0
info:
  title: Vert.x API
  version: "1"
servers:
- url: https://virtserver.swaggerhub.com/b-iot/Vert.x/1
  description: SwaggerHub API Auto Mocking
paths:
  /relays:
    get:
      tags:
      - Relay
      description: returns all relays
      operationId: getRelays
      parameters:
      - name: offset
        in: query
        description: number of records to skip
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        description: max number of records to return
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: All the relays
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Relay'
    post:
      tags:
      - Relay
      operationId: registerRelay
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RelayRegisterInfo'
      responses:
        "200":
          description: the registered relay
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Relay'
  /relays/{id}:
    get:
      tags:
      - Relay
      description: returns a specific relay
      operationId: getRelay
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: a relay
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Relay'
    put:
      tags:
      - Relay
      description: updates a specific relay
      operationId: updateRelay
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RelayUpdateInfo'
      responses:
        "200":
          description: the updated relay
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Relay'
    delete:
      tags:
      - Relay
      description: deletes a specific relay
      operationId: deleteRelay
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successfully deleted relay
  /users:
    get:
      tags:
      - User
      description: returns all users
      operationId: getUsers
      parameters:
      - name: offset
        in: query
        description: number of users to skip
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        description: max number of users to return
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: All the users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags:
      - User
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterInfo'
      responses:
        "200":
          description: the registered user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/authenticate:
    post:
      tags:
      - User
      operationId: authenticate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAuthenticateInfo'
      responses:
        "200":
          description: The company of the authenticated user as a string
          content:
            text/plain:
              schema:
                type: string
                example: biot
        "401":
          description: Authentication error
  /users/{id}:
    get:
      tags:
      - User
      description: returns a specific user
      operationId: getUser
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: a user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      tags:
      - User
      description: updates a specific user
      operationId: updateUser
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdateInfo'
      responses:
        "200":
          description: the updated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      tags:
      - User
      description: deletes a specific user
      operationId: deleteUser
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successfully deleted user
  /items:
    get:
      tags:
      - Item
      description: returns all items
      operationId: getItems
      parameters:
      - name: offset
        in: query
        description: number of items to skip
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        description: max number of items to return
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: All the items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
    post:
      tags:
      - Item
      operationId: registerItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemRegisterInfo'
      responses:
        "200":
          description: the registered item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
  /items/{id}:
    get:
      tags:
      - Item
      description: returns a specific item
      operationId: getItem
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: an item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        "404":
          description: Item not found
    put:
      tags:
      - Item
      description: updates a specific item
      operationId: updateItem
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemUpdateInfo'
      responses:
        "200":
          description: the updated item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    delete:
      tags:
      - Item
      description: deletes a specific item
      operationId: deleteItem
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successfully deleted item
components:
  schemas:
    Relay:
      type: object
      properties:
        mqttID:
          type: string
        mqttUsername:
          type: string
        relayID:
          type: string
        ledStatus:
          type: boolean
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
        lastModified:
          type: string
          format: date-time
        wifi:
          $ref: '#/components/schemas/Relay_wifi'
      description: A relay
    RelayRegisterInfo:
      type: object
      properties:
        mqttID:
          type: string
        mqttUsername:
          type: string
        mqttPassword:
          type: string
          format: password
        relayID:
          type: string
        ledStatus:
          type: boolean
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
        wifi:
          $ref: '#/components/schemas/Relay_wifi'
      description: A relay to register
    RelayUpdateInfo:
      type: object
      properties:
        ledStatus:
          type: boolean
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
        wifi:
          $ref: '#/components/schemas/Relay_wifi'
        beacon:
          $ref: '#/components/schemas/RelayUpdateInfo_beacon'
      description: Update information for a relay
    User:
      type: object
      properties:
        userID:
          type: string
        username:
          type: string
        company:
          type: string
      description: A user
    UserRegisterInfo:
      type: object
      properties:
        userID:
          type: string
        username:
          type: string
        password:
          type: string
          format: password
        company:
          type: string
      description: A user to register
    UserUpdateInfo:
      type: object
      properties:
        company:
          type: string
      description: Update information for a user
    UserAuthenticateInfo:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          format: password
      description: Authenticate information for a user
    Item:
      type: object
      properties:
        id:
          type: integer
        beacon:
          type: string
        category:
          type: string
        service:
          type: string
        timestamp:
          type: string
          format: date-time
        battery:
          maximum: 100
          minimum: 0
          type: integer
          format: int32
        status:
          type: string
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
      description: An item
    ItemRegisterInfo:
      type: object
      properties:
        beacon:
          type: string
        category:
          type: string
        service:
          type: string
      description: An item to register
    ItemUpdateInfo:
      type: object
      properties:
        beacon:
          type: string
        category:
          type: string
        service:
          type: string
      description: Update information for an item
    Relay_wifi:
      type: object
      properties:
        ssid:
          type: string
        password:
          type: string
          format: password
    RelayUpdateInfo_beacon:
      type: object
      properties:
        mac:
          type: string
        txPower:
          type: integer
          format: int32
