apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: triangulation
  name: triangulation
spec:
  selector:
    matchLabels:
      app: triangulation
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: triangulation
    spec:
      containers:
      - image: vertx-backend/triangulation:latest
        name: triangulation
        env:
          - name: KAFKA_PORT
            valueFrom:
              configMapKeyRef:
                name: relays-communication-config
                key: kafka_port
          - name: KAFKA_HOST
            valueFrom:
              configMapKeyRef:
                name: relays-communication-config
                key: kafka_hostname
          - name: TIMESCALE_PORT
            valueFrom:
              configMapKeyRef:
                name: crud-config
                key: timescale_port
          - name: TIMESCALE_HOST
            valueFrom:
              configMapKeyRef:
                name: crud-config
                key: timescale_hostname