apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: public-api
  name: public-api
spec:
  selector:
    matchLabels:
      app: public-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: public-api
    spec:
      containers:
        - image: vertx-backend/public-api:latest
          name: public-api
          ports:
            - name: http
              containerPort: 8080
            - name: hazelcast
              containerPort: 5701
          env:
            - name: CRUD_HOST
              valueFrom:
                configMapKeyRef:
                  name: crud-config
                  key: crud_hostname
            - name: CRUD_PORT
              valueFrom:
                configMapKeyRef:
                  name: crud-config
                  key: crud_port
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
