apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: public-api
  name: public-api
spec:
  selector:
    matchLabels:
      app: public-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: public-api
    spec:
      containers:
        - image: vertx-backend/public-api:latest
          name: public-api
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8080
            - name: hazelcast
              containerPort: 5701
          env:
            - name: JAVA_TOOL_OPTIONS
              value: --add-modules=java.se --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED
            - name: CRUD_HOST
              valueFrom:
                configMapKeyRef:
                  name: crud-config
                  key: crud_hostname
            - name: CRUD_PORT
              valueFrom:
                configMapKeyRef:
                  name: crud-config
                  key: crud_port
            - name: RELAYS_COMMUNICATION_HOST
              valueFrom:
                configMapKeyRef:
                  name: relays-communication-config
                  key: relays-communication-hostname
            - name: RELAYS_COMMUNICATION_PORT
              valueFrom:
                configMapKeyRef:
                  name: relays-communication-config
                  key: relays-communication-port
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
