apiVersion: v1
kind: Service
metadata:
  labels:
    app: public-api
  name: public-api-external
spec:
  type: LoadBalancer
  loadBalancerIP: "35.205.47.121"
  selector:
    app: public-api
  ports:
    - name: http
      port: 8080
