apiVersion: v1
kind: Service
metadata:
  labels:
    app: crud
    vertx-backend: hazelcast
  name: crud
spec:
  type: ClusterIP
  selector:
    app: crud
  ports:
    - name: http
      port: 8080
    - name: hazelcast
      port: 5701
